# Generated by Django 3.2 on 2022-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
